[package]
name = "reinstinct-cpu"
version = "0.1.0"
edition = "2024"

[dependencies]
reinstinct-gguf = { path = "../gguf" }
reinstinct-model = { path = "../model" }
reinstinct-quant = { path = "../quant" }
rayon.workspace = true
tracing.workspace = true
half.workspace = true
thiserror.workspace = true
